app:
    resource: "@AppBundle/Controller/"
    type:     annotation

root_url:
  path: '/'
  defaults: { _controller: AppBundle:Front:index }

show_path:
  path: '/show'
  defaults: { _controller: AppBundle:Front:show }
# posts_path:
#   path: '/posts'
#   defaults: { _controller: AppBundle:Post:index }

# show_post_path:
#   path: '/posts/show/{id}'
#   defaults: { _controller: AppBundle:Post:show }

user_api_path:
  path: '/api/user'
  defaults: { _controller: AppBundle\Controller\Api\Mobile\ApiBaseController::userAction }
  methods: [POST]

web_api_path:
  path: '/api/school/categories/{id}'
  defaults: { _controller: AppBundle\Controller\Api\Mobile\ApiBaseController::categoryActoin, id: 1 }
  requirements:
    page:  \d{1, 6}
  methods: [GET]

web_test_index:
  path: /web/{name}
  defaults: {_controller: 'AppBundle\Controller\WebTest\HomeController::indexAction'}
