acme_mobile:
    resource: "@AcmeMobileBundle/Controller/"
    type:     annotation
    prefix:   /api/mobile
    
acme_webui:
     resource: "@AcmeWebUIBundle/Resources/config/routing.yml"
     prefix: /webui

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

app_main_urls:
  resource: "@AppBundle/Resources/config/routing.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

root_url:
  path: '/'
  defaults: { _controller: AppBundle:Front:index }

