# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  my_service.logger:
    class: Symfony\Bridge\Monolog\Logger
    arguments: [app]
    calls:
      - [pushHandler, [@my_service.logger_handler]]

  my_service.logger_handler:
    class:  Monolog\Handler\StreamHandler
    arguments: [%kernel.logs_dir%/%kernel.environment%_my.log]

  # my_web_calculator:
  #   class: AppBundle\Utility\WebTest\WebCalculator
  #   arguments: ["@serializer"]

