n acme_web_ui_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeWebUIBundle:Default:index }

#教师

teacher_search_path:
  path: '/account/teacher/search'
  defaults: { _controller: AcmeWebUIBundle:Teacher:search }

teacher_index_path:
  path: '/account/teacher/index'
  defaults: { _controller: AcmeWebUIBundle:Teacher:index }

teacher_edit_path:
  path: '/account/teacher/{id}/edit'
  defaults: { _controller: AcmeWebUIBundle:Teacher:edit }

teacher_delete_path:
  path: '/account/teacher/{id}'
  defaults: { _controller: AcmeWebUIBundle:Teacher:delete }
  requirements:
      _method:  DELETE

teacher_new_path:
  path: '/account/teacher/new'
  defaults: { _controller: AcmeWebUIBundle:Teacher:new }

#友情链接关于我们

friendly_index_path:
  path: '/account/friendly/index'
  defaults: { _controller: AcmeWebUIBundle:Friendly:index }

friendly_delete_path:
  path: '/account/friendly/{id}'
  defaults: { _controller: AcmeWebUIBundle:Friendly:delete }
  requirements:
      _method:  DELETE

friendly_new_path:
  path: '/account/friendly/new'
  defaults: { _controller: AcmeWebUIBundle:Friendly:new }

#友情链接学习

learn_new_path:
  path: '/account/learn/new'
  defaults: { _controller: AcmeWebUIBundle:Learn:new }

learn_delete_path:
  path: '/account/learn/{id}'
  defaults: { _controller: AcmeWebUIBundle:Learn:delete }
  requirements:
      _method:  DELETE

#友情链接帮助

help_delete_path:
  path: '/account/help/{id}'
  defaults: { _controller: AcmeWebUIBundle:Help:delete }
  requirements:
      _method:  DELETE

help_new_path:
  path: '/account/help/new'
  defaults: { _controller: AcmeWebUIBundle:Help:new }

#友情链接合作

partner_delete_path:
  path: '/account/partner/{id}'
  defaults: { _controller: AcmeWebUIBundle:Partner:delete }
  requirements:
      _method:  DELETE

partner_new_path:
  path: '/account/partner/new'
  defaults: { _controller: AcmeWebUIBundle:Partner:new }

#友情链接下载

down_delete_path:
  path: '/account/down/{id}'
  defaults: { _controller: AcmeWebUIBundle:Down:delete }
  requirements:
      _method:  DELETE

down_new_path:
  path: '/account/down/new'
  defaults: { _controller: AcmeWebUIBundle:Down:new }

#轮播图

pictures_delete_path:
  path: '/account/pictures/{id}'
  defaults: { _controller: AcmeWebUIBundle:Pictures:delete }
  requirements:
      _method:  DELETE

pictures_new_path:
  path: '/account/pictures/new'
  defaults: { _controller: AcmeWebUIBundle:Pictures:new }

pictures_index_path:
  path: '/account/pictures/index'
  defaults: { _controller: AcmeWebUIBundle:Pictures:index }

#学币管理
coin_person_path:
  path: '/account/coin/person'
  defaults: { _controller: AcmeWebUIBundle:Coin:person }

coin_edit_path:
  path: '/account/coin/{id}/edit'
  defaults: { _controller: AcmeWebUIBundle:Coin:edit }

#账户管理

account_modify_path:
  path: '/account/acount/{id}/modify'
  defaults: { _controller: AcmeWebUIBundle:Account:modify }

account_edit_path:
  path: '/account/account/{id}/edit'
  defaults: { _controller: AcmeWebUIBundle:Account:edit }

account_index_path:
  path: '/account/account/index'
  defaults: { _controller: AcmeWebUIBundle:Account:index }

account_person_path:
  path: '/account/account/person'
  defaults: { _controller: AcmeWebUIBundle:Account:person }


#省份管理

area_new_path:
  path: '/account/area/new'
  defaults: { _controller: AcmeWebUIBundle:Area:new }

area_delete_path:
  path: '/account/area/{id}'
  defaults: { _controller: AcmeWebUIBundle:Area:delete }
  requirements:
      _method:  DELETE

area_index_path:
  path: '/account/area'
  defaults: { _controller: AcmeWebUIBundle:Area:index }

#摄像头管理

camera_search_path:
  path: '/account/camera/search'
  defaults: { _controller: AcmeWebUIBundle:Camera:search }

camerauser_edit_path:
  path: '/account/camerauser/{id}/edit'
  defaults: { _controller: AcmeWebUIBundle:Camerauser:edit }

camera_index_path:
  path: '/account/camera'
  defaults: { _controller: AcmeWebUIBundle:Camera:index }

camera_new_path:
  path: '/account/camera/new'
  defaults: { _controller: AcmeWebUIBundle:Camera:new }

camera_delete_path:
  path: '/account/camera/{id}'
  defaults: { _controller: AcmeWebUIBundle:Camera:delete }
  requirements:
        _method:  DELETE

#课程管理

course_search_path:
  path: '/account/course/search'
  defaults: { _controller: AcmeWebUIBundle:Course:search }

course_index_path:
  path: '/account/course'
  defaults: { _controller: AcmeWebUIBundle:Course:index }

course_edit_path:
  path: '/account/course/{id}/edit'
  defaults: { _controller: AcmeWebUIBundle:Course:edit }

course_delete_path:
  path: '/account/course/{id}'
  defaults: { _controller: AcmeWebUIBundle:Course:delete }
  requirements:
        _method:  DELETE

course_create_path:
  path: '/account/course/create'
  defaults: { _controller: AcmeWebUIBundle:Course:create }

  
#会员管理

user_person_path:
  path: '/account/user/{id}/person'
  defaults: { _controller: AcmeWebUIBundle:User:person }

user_create_path:
  path: '/account/user/{id}/create'
  defaults: { _controller: AcmeWebUIBundle:User:create }

user_new_path:
  path: '/account/user/new'
  defaults: { _controller: AcmeWebUIBundle:User:new }

user_edit_path:
  path: '/account/user/{id}/edit'
  defaults: { _controller: AcmeWebUIBundle:User:edit }

user_delete_path:
  path: '/account/user/{id}'
  defaults: { _controller: AcmeWebUIBundle:User:delete }
  requirements:
        _method:  DELETE

user_index_path:
  path: '/account/user/index'
  defaults: { _controller: AcmeWebUIBundle:User:index }

user_search_path:
  path: '/account/user/search'
  defaults: { _controller: AcmeWebUIBundle:User:search }

user_complete_path:
  path: '/account/user/complete'
  defaults: { _controller: AcmeWebUIBundle:User:complete }

amdin_setting_path:
  path: '/account/admin/setting'
  defaults: { _controller: AcmeWebUIBundle:User:admin }

#前台页面

front_path:
  path: '/'
  defaults: { _controller: AcmeWebUIBundle:Front:index }

front_course_path:
  path: '/courses'
  defaults: { _controller: AcmeWebUIBundle:Front:course }

front_teacher_path:
  path: '/teachers'
  defaults: { _controller: AcmeWebUIBundle:Front:teacher }

front_about_path:
  path: '/about'
  defaults: { _controller: AcmeWebUIBundle:Front:about }

front_info_path:
  path: '/info'
  defaults: { _controller: AcmeWebUIBundle:Front:info }

front_mobile_path:
  path: '/mobile'
  defaults: { _controller: AcmeWebUIBundle:Mobile:index }

front_mobile_category_path:
  path: '/mobile/category'
  defaults: { _controller: AcmeWebUIBundle:Mobile:category }

front_mobile_teacher_path:
  path: '/mobile/teacher/'
  defaults: { _controller: AcmeWebUIBundle:Mobile:teacher }

front_mobile_teacher_info_path:
  path: '/mobile/teacher/{id}'
  defaults: { _controller: AcmeWebUIBundle:Mobile:teacherinfo }

front_mobile_course_path:
  path: '/mobile/course/{id}'
  defaults: { _controller: AcmeWebUIBundle:Mobile:course }

front_mobile_about_path:
  path: '/mobile/aboutus'
  defaults: { _controller: AcmeWebUIBundle:Mobile:about }