acme_web_ui_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeWebUIBundle:Default:index }

coin_edit_path:
  path: '/account/coin/{id}/edit'
  defaults: { _controller: AcmeWebUIBundle:Coin:edit }

account_edit_path:
  path: '/account/account/{id}/edit'
  defaults: { _controller: AcmeWebUIBundle:Account:edit }

account_index_path:
  path: '/account/account/index'
  defaults: { _controller: AcmeWebUIBundle:Account:index }

area_new_path:
  path: '/account/area/new'
  defaults: { _controller: AcmeWebUIBundle:Area:new }

area_delete_path:
  path: '/account/area/{id}'
  defaults: { _controller: AcmeWebUIBundle:Area:delete }
  requirements:
      _method:  DELETE

area_index_path:
  path: '/account/area'
  defaults: { _controller: AcmeWebUIBundle:Area:index }

camerauser_edit_path:
  path: '/account/camerauser/{id}/edit'
  defaults: { _controller: AcmeWebUIBundle:Camerauser:edit }

camera_index_path:
  path: '/account/camera'
  defaults: { _controller: AcmeWebUIBundle:Camera:index }

camera_new_path:
  path: '/account/camera/new'
  defaults: { _controller: AcmeWebUIBundle:Camera:new }

camera_delete_path:
  path: '/account/camera/{id}'
  defaults: { _controller: AcmeWebUIBundle:Camera:delete }
  requirements:
        _method:  DELETE

user_create_path:
  path: '/account/user/{id}/create'
  defaults: { _controller: AcmeWebUIBundle:User:create }

user_new_path:
  path: '/account/user/new'
  defaults: { _controller: AcmeWebUIBundle:User:new }

user_edit_path:
  path: '/account/user/{id}/edit'
  defaults: { _controller: AcmeWebUIBundle:User:edit }

user_delete_path:
  path: '/account/user/{id}'
  defaults: { _controller: AcmeWebUIBundle:User:delete }
  requirements:
        _method:  DELETE

user_index_path:
  path: '/account/user/index'
  defaults: { _controller: AcmeWebUIBundle:User:index }

amdin_setting_path:
  path: '/account/admin/setting'
  defaults: { _controller: AcmeWebUIBundle:User:admin }

front_path:
  path: '/'
  defaults: { _controller: AcmeWebUIBundle:Front:index }

front_course_path:
  path: '/courses'
  defaults: { _controller: AcmeWebUIBundle:Front:course }

front_teacher_path:
  path: '/teachers'
  defaults: { _controller: AcmeWebUIBundle:Front:teacher }

front_about_path:
  path: '/about'
  defaults: { _controller: AcmeWebUIBundle:Front:about }

front_info_path:
  path: '/info'
  defaults: { _controller: AcmeWebUIBundle:Front:info }

front_mobile_path:
  path: '/mobile'
  defaults: { _controller: AcmeWebUIBundle:Mobile:index }

front_mobile_category_path:
  path: '/mobile/category'
  defaults: { _controller: AcmeWebUIBundle:Mobile:category }

front_mobile_teacher_path:
  path: '/mobile/teacher/'
  defaults: { _controller: AcmeWebUIBundle:Mobile:teacher }

front_mobile_teacher_info_path:
  path: '/mobile/teacher/{id}'
  defaults: { _controller: AcmeWebUIBundle:Mobile:teacherinfo }

front_mobile_course_path:
  path: '/mobile/course/{id}'
  defaults: { _controller: AcmeWebUIBundle:Mobile:course }

front_mobile_about_path:
  path: '/mobile/aboutus'
  defaults: { _controller: AcmeWebUIBundle:Mobile:about }